// <auto-generated />
namespace Grupo14_ONG_DA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class pablo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pablo));
        
        string IMigrationMetadata.Id
        {
            get { return "202103051606524_pablo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
